### ISSUE TITLE
Project not compiled without /static folder.

### ISSUE THREAD

**Issue by RRROOOMMM** [brunosimon/three.js-template#2]
Hi, just to try that boilerplate and find some problems:
1) Project not compile without /src folder
2) Here is no info that template required Parcel.js installed globally

And thanks for that template. And I fix that problems on pull request, please just check it.

**Comment by brunosimon** [comment]
I just pushed a new version that don't even use the static folder. Check the commits if you want to see what's new.
Thanks for the report.
